apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: inspections.amun.thoth-station.ninja
spec:
  group: amun.thoth-station.ninja
  names:
    kind: Inspection
    listKind: InspectionList
    plural: inspections
    singular: inspection
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
