apiVersion: amun.thoth-station.ninja/v1alpha1
kind: Inspection
metadata:
  name: "example-inspection"
spec:
  source:
    git:
      uri: "https://github.com/openshift/django-ex.git"
      ref: "master"
    sourceStrategy:
      name: "python-36-centos7:latest"
  buildEnvironment:
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
        cpu_family: 6
        cpu_model: 94
        physical_cpu_total: 2
  runtimeEnvironment:
    resources:
      requests:
        cpu: "1000m"
        memory: "512Mi"
        cpu_family: 6
        cpu_model: 94
        physical_cpu_total: 2
